apiVersion: backstage.io/v1alpha1
kind: Cluster
metadata:
  name: "ClusterA"
  annotations:
    github.com/project-slug: ValberJunior/ClusterA
    backstage.io/techdocs-ref: dir:.
    github.com/workflows: terraform-deploy.yml,terraform-destroy.yml
spec:
  type: iac
  lifecycle: production
  owner: "group:default/admin"
  
