apiVersion: backstage.io/v1alpha1
kind: Cluster
metadata:
  name: "ClusterA"
  environment:
    k8s_version: 1.28
    cidr_block: 10.50.0.0/16
    instance_type: typeX
    capacity_type: 111
    node_quantity: 08
    domain: test.com
    hosted_Zone_Id: sfdfsjfs
    role_arn: testerole 
    vpc: xpto-vpc
    nginx: xpto-nginx
    cert_Manager_Issuer_Type: staging
    cert_Manager_Email: valber@teste.com
    subnet_publics:
    - 10.50.1.0/24
    - 10.50.2.0/24
    - 10.50.3.0/24
    private_publics:
    - 10.50.4.0/24
    - 10.50.5.0/24
    - 10.50.6.0/24   
  annotations:
    github.com/project-slug: ValberJunior/ClusterA
    backstage.io/techdocs-ref: dir:.
    github.com/workflows: terraform-deploy.yml,terraform-destroy.yml
spec:
  type: iac
  lifecycle: production
  owner: "group:default/admin"
