apiVersion: backstage.io/v1alpha1
kind: Cluster
metadata:
  name: "ClusterA"
#  labels:
#    domain: vee.codes
#    hostedZoneId: sfdfsjfs
#    vpc: xpto-vpc
#    certManagerEmail: teste@teste.com
#    certManagerIssuerType: staging    
  labels:
    environment: production
    app: nginx
    domain: vee.codes
    hostedZoneId: sfdfsjfs
    vpc: xpto-vpc
    certManagerEmail: teste@gmail.com
    certManagerIssuerType: staging
  annotations:
    github.com/project-slug: ValberJunior/ClusterA
    backstage.io/techdocs-ref: dir:.
    github.com/workflows: terraform-deploy.yml,terraform-destroy.yml
spec:
  type: iac
  lifecycle: production
  owner: "group:default/admin"
